teams:
# new team stanza for team kubrix
  - name: kubrix
    sourceRepos:
      - 'https://github.com/jkleinlercher/kubrix-*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/jkleinlercher/kubrix-apps
      path: demo-apps
      revision: main
    multiStageKargoAppSet:
      github:
        organization: jkleinlercher
